spring.datasource.url=jdbc:mysql://localhost:3306/soulm_database
spring.datasource.username=root
spring.datasource.password=1234

app.require-ssl=false
app.frontend-url=http://localhost:3000

jwt.secret=bhmrxzdRa3nA0XZ7d+V7EBD8nMjX2GeDWzP4xxy4Gl3dLScFhPuTuWLEImOHyMvMJGoY5CyDKeg2a7G9ZGiHBg==

spring.mail.username=soulm.dating@gmail.com
spring.mail.password=tyvh mzrg eobo ohcp

aws.accessKeyId=${AWS_ACCESS_KEY_ID}
aws.secretKey=${AWS_SECRET_ACCESS_KEY}